### ISSUE TITLE
Error on load [invalid date format]

### ISSUE THREAD

**Issue by jeroenverfallie** [mockko/livereload#101]
Hi, ever since I reinstalled livereload, it seems to throw me this error:

> $ livereload
> Invalid gemspec in [c:/Ruby187/lib/ruby/gems/1.8/specifications/em-websocket-0.3.5.gemspec]: invalid date format in specification: "2011-10-24 00:00:00.000000000Z"
> c:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:53:in `gem_original_require': no such file to load -- em websocket (LoadError) 
> 
> from c:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:53:in `require'
> from c:/Ruby187/lib/ruby/gems/1.8/gems/livereload-1.6/bin/../lib/livereload.rb:1
> from c:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:53:in`gem_original_require'
> from c:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:53:in `require'
> from c:/Ruby187/lib/ruby/gems/1.8/gems/livereload-1.6/bin/livereload:3
> from c:/Ruby187/bin/livereload:19:in`load'
> from c:/Ruby187/bin/livereload:19

I checked previous issues, but did not find a similar one.

Thanks.

**Comment by tiw** [comment]
I met the same problem with ubuntu, ruby 1.8.7

**Comment by mriffault** [comment]
Hi,
Same issue, ruby 1.8.7. Have to update ruby ? and how to...?
Best regards,

**Comment by tiw** [comment]
edit c:/Ruby187/lib/ruby/gems/1.8/specifications/em-websocket-0.3.5.gemspec
change 2011-10-24 00:00:00.000000000Z to 2011-10-24

**Comment by ksamuel** [comment]
Same issue. Everytime I install a gem, I feel like I'm tossing a coin: will it work ?

**Comment by saltcod** [comment]
Same on Snow Leopard.
