### ISSUE TITLE
Chrome Developer Tools should update when CSS changes are applied

### ISSUE THREAD

**Issue by ndbroadbent** [mockko/livereload#104]
### Steps to Reproduce:
1. Open a page in chrome, and start live reload
2. Start Chrome developer tools and view the CSS for an element
3. Change the css in the css file, and save the file. The browser will update and display the new CSS
### Expected Result:
- Chrome Developer Tools should refresh it's state to show the changed CSS
### Actual Result
- Chrome Developer Tools must be manually refreshed with a mouse click.

It would be awesome if this was possible! Thanks

**Comment by NV** [comment]
The problem is in the Chrome DevTools. You should rather report it to http://webkit.org/new-inspector-bug
