### ISSUE TITLE
UI: alert message is annoying

### ISSUE THREAD

**Issue by NV** [mockko/livereload#14]
![alert](http://elv1s.ru/i/livereload-alert.png)

Can we just change icon color to gray?

**Comment by andreyvit** [comment]
Missed this issue… The message should help catch server crashes. I guess the server was meant for a start-and-forget usage mode, rather than starting and stopping it often.

Mind explaining why you are stopping it?

**Comment by andreyvit** [comment]
Since there was no more feedback on this issue, did not change anything in LiveReload 1.4. Please help us understand your use cases if you want this fixed in the next version of LiveReload.

**Comment by NV** [comment]
I can't run it from `~` and forget about it http://github.com/mockko/livereload/issues#issue/17 , so I have to switch directories frequently.

**Comment by andreyvit** [comment]
Why don't you just specify all the directories you need on the command line? LiveReload accepts several directories, that's how I'm using it myself.

**Comment by NV** [comment]
That's a good solution! I was lazy to do a list of directories I actually need (it's pretty big).

Also, last time I tried to do a restart, that alert message prevents it (I had to do a restart because of some Mac OS X update). It happened just once, so it's doesn't matter much.

**Comment by andreyvit** [comment]
OK, restart is a good argument. Since LR hasn't ever been crashing randomly (it either works from the start or not), I think it's safe to remove it in the next version (and instead alert only when the connection fails).

**Comment by dottedmag** [comment]
Implemented.

**Comment by NV** [comment]
Closed.

**Comment by dottedmag** [comment]
Not yet closed, fix is not released yet.

**Comment by NV** [comment]
LiveReload 1.5 Chrome extension and Safari extension have been released.
Closed by 38532bd8a0b3c556ef72d84d47fec1c3a6fd4d7a
Closed by 38532bd8a0b3c556ef72d84d47fec1c3a6fd4d7a
Closed by 38532bd8a0b3c556ef72d84d47fec1c3a6fd4d7a
