### ISSUE TITLE
Browser uses stale cached static files after page refresh.

### ISSUE THREAD

**Issue by dottedmag** [mockko/livereload#15]
Load page. Change .css file. LiveReload will request style.css?livereload=1. Browser will load and cache this file.

Now manually refresh page. Change .css file again. LiveReload will request style.css?livereload=1 again. Browser will happily use stale cached file.

**Comment by dottedmag** [comment]
Fixed in trunk. Extensions need to be published still.

**Comment by andreyvit** [comment]
This change is now released as LiveReload 1.4.
