### ISSUE TITLE
Livereload doesn't work with rvm

### ISSUE THREAD

**Issue by bartkozal** [mockko/livereload#18]
```
$ rvm 1.8.7 
$ livereload

/Users/ooo/.rvm/rubies/ruby-1.8.7-p299/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- osx/foundation (LoadError)
from /Users/ooo/.rvm/rubies/ruby-1.8.7-p299/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac/rubycocoa_watcher.rb:2
from /Users/ooo/.rvm/rubies/ruby-1.8.7-p299/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /Users/ooo/.rvm/rubies/ruby-1.8.7-p299/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac.rb:16:in `initialize'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/invokers/subprocess_invoker.rb:61:in `call'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/invokers/subprocess_invoker.rb:61:in `start_subprocess'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/invokers/subprocess_invoker.rb:20:in `initialize'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac.rb:25:in `new'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac.rb:25:in `initialize'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/monitor.rb:35:in `new'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/monitor.rb:35:in `watch'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/livereload-1.4/bin/../lib/livereload.rb:175:in `restart_watching'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/livereload-1.4/bin/../lib/livereload.rb:243:in `run'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/livereload-1.4/bin/../lib/livereload.rb:243:in `each'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/livereload-1.4/bin/../lib/livereload.rb:243:in `run'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/livereload-1.4/bin/../lib/livereload.rb:215:in `run'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/gems/livereload-1.4/bin/livereload:51
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/bin/livereload:19:in `load'
from /Users/ooo/.rvm/gems/ruby-1.8.7-p299/bin/livereload:19
```

**Comment by andreyvit** [comment]
OK, there's an almost-finished alternate backend that does not use Ruby Cocoa. I will finish it some time later, but if someone can possibly step in and help, would be appreciated a lot.

See `lib/em-dir-watcher/platform/mac/ffi_fsevents_watcher.rb` in em-dir-watcher gem (NOT LiveReload gem) — http://github.com/mockko/em-dir-watcher. FFI has virtually no docs, but it does have a comprehensive rspec test suite, and I've been able to figure everything from it.

**Comment by dottedmag** [comment]
I am closing this issue as duplicate to newly created umbrella #24 (get rid of RubyCocoa).

**Comment by NV** [comment]
Having same troubles. Found [Install RubyCocoa on RVM](http://rbxbx.tumblr.com/post/556343148/install-rubycocoa-on-rvm), but it doesn't work for me.

```
➤ ruby install.rb config --build-universal=yes
config: unknown option --build-universal=yes
➤ ruby install.rb config 
install.rb: entering config phase...
create ext/rubycocoa/extconf.rb
create framework/GeneratedConfig.xcconfig
create framework/src/objc/Version.h
create tests/Makefile
---> framework
create /Users/nv/Downloads/RubyCocoa-1.0.1/framework/src/objc/osx_ruby.h ...
config failed
hook /Users/nv/Downloads/RubyCocoa-1.0.1/framework/post-config.rb failed:
No such file or directory - /Users/nv/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/x86_64-darwin10.4.0/ruby.h
```

RubyCocoa-1.0.1

**Comment by NV** [comment]
Trying Ruby 1.8.7

<pre>
➤ ruby install.rb setup
...
install.rb: setup done.
➤ ruby install.rb install
install.rb: entering install phase...
rm -rf '/tmp/rubycocoa_backup/sample'
mkdir -p '/tmp/rubycocoa_backup'
mv '/Developer/Examples/RubyCocoa' '/tmp/rubycocoa_backup/sample'
mv: rename /Developer/Examples/RubyCocoa to /tmp/rubycocoa_backup/sample: Permission denied
install failed
hook /Users/nv/Downloads/RubyCocoa-1.0.1/./pre-install.rb failed:
'system mv '/Developer/Examples/RubyCocoa' '/tmp/rubycocoa_backup/sample'' failed
➤ sudo ruby install.rb install
...
install.rb: install done.</pre>


Everything good so far. Let's run livereload

<pre>➤ livereload 

Version:  1.4  (compatible with browser extension versions 1.4.x)
Port:     35729
Watching: /Users/nv/Sites/kulesh.info
  - extensions: .html .css .js .png .gif .jpg .php .php5 .py .rb .erb
  - live refreshing disabled for .js: will reload the whole page when .js is changed
  - excluding changes in: */.git/* */.svn/* */.hg/*
  - with a grace period of 0.05 sec after each change

LiveReload is waiting for browser to connect.
dyld: lazy symbol binding failed: Symbol not found: _RBRubyCocoaInit
  Referenced from: /Users/nv/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/site_ruby/1.8/i686-darwin10.4.0/rubycocoa.bundle
  Expected in: flat namespace

dyld: Symbol not found: _RBRubyCocoaInit
  Referenced from: /Users/nv/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/site_ruby/1.8/i686-darwin10.4.0/rubycocoa.bundle
  Expected in: flat namespace</pre>


Now we have another problem: #24

**Comment by jmeiss** [comment]
Exactly the same problem for me. No solution yet?

**Comment by NV** [comment]
Nope. You can try [guard-livereload](http://github.com/guard/guard-livereload) instead. It does not use Ruby Cocoa, so it should be compatible with rvm.

**Comment by jmeiss** [comment]
Nice it works like a charm! Thanks :)
