### ISSUE TITLE
Safari 5 crash with 1.2.1

### ISSUE THREAD

**Issue by DuoSRX** [mockko/livereload#2]
When right-clicking and selecting "Enable LiveReload", Safari crash without any error message.
In the console there is just "Browser connected. Browser disconnected."

Safari Version 5.0 (6533.16), LiveReload 1.2.1, OSX 10.6.4, project is a php project.

**Comment by julienXX** [comment]
Same problem here with a Rails project and the same config.

**Comment by andreyvit** [comment]
This is a known bug: when livereload attemps to monitor too many files (via a lame per-file watching API from EventMachine), it runs out of open file limit, throws an exception and disconnects the WebSocket. Disconnection during handshake triggers some bug in Safari and it crashes.

Please try to increase ulimit -n from default 256 to something bigger:

```
ulimit -n 4096
livereload
```

I'm certainly rewriting the command-line tool to use something like fssm soon. Sorry for this issue.

**Comment by DuoSRX** [comment]
Hmmm didn't change a thing. The project I use has A LOT of file (something like 12000), and it seems there is a hard limit of 10240 files per process :

$ sysctl kern.maxfiles kern.maxfilesperproc
kern.maxfiles: 12288
kern.maxfilesperproc: 10240

**Comment by andreyvit** [comment]
Right, you need ulimit at least as high as the number of files you have. I guess you'll have to wait for fssm-based command-line tool which is coming real soon (next few days probably).

**Comment by DuoSRX** [comment]
Alright. I'll close this one then :)
