### ISSUE TITLE
Reverting a version (of browser extension)?

### ISSUE THREAD

**Issue by orlin** [mockko/livereload#23]
I know there are a couple of other issues about problems with 1.4 and I don't mean to create extra heat, but is there a way to revert back to 1.3?  

I guess Chrome auto-upgraded and asked me to update the gem.  After installing RubyCocoa, I started getting eventmachine-0.12.10/lib/eventmachine.rb:572:in `start_tcp_server': no acceptor (RuntimeError).  I'm guessing that's the "rvm error"?  Anyway, I uninstalled 1.4.  1.3 livereload server says "Browser connected." - but Chrome doesn't reload.  I'm guessing because it's using version 1.4 (the extension).  Is there a way to switch back to an older extension and have it stay that way (until this is fixed)?

**Comment by bitboxer** [comment]
I would say that the problem should be fixed. Make a ticket for that and don't go the "easy" way around that problem. Other people could get into the same problem as you did.

**Comment by orlin** [comment]
I bet the problem will be fixed.  All I'm asking is if there is a way to still use livereload (while it's being fixed).  It seems there are already 2 other tickets for this issue.  Has everyone stopped using it?

**Comment by dottedmag** [comment]
The easy way to get older extension is to clone git repo, check out v1.3 tag and install extension from LiveReload.chromeextension directory.

**Comment by orlin** [comment]
Thank you.  This works well for now.  With Chrome (at least).

**Comment by dottedmag** [comment]
Nice. Closing the issue then.

**Comment by dottedmag** [comment]
Reopen and tag as 'known-issue'

**Comment by tgraham** [comment]
So when is a fix for this supposed to be ready? Seems harsh that we have to clone the 1.3 branch and wait.

**Comment by dottedmag** [comment]
Who knows? As free time permits to. It's not a simple "fix", it's a rewrite.

**Comment by tgraham** [comment]
So 1.4 was a complete rewrite of 1.3? Hope you find it soon, LR is awesome sauce.

**Comment by dottedmag** [comment]
Yep, 1.4 gem uses completely different file watching backend which solved lot of problems (and introduced some). Fixing this issue means rewriting OS X support once again, but at least Windows and Linux code work fine.

**Comment by NV** [comment]
Closing it. Dup of [#26 RubyCocoa is not reliable, get rid of using it (osx/foundation issues etc)](https://github.com/mockko/livereload/issues#issue/26).
