### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _RBRubyCocoaInit

### ISSUE THREAD

**Issue by attaboy** [mockko/livereload#24]
I did a song and dance to install RubyCocoa and livereload on top of ree 1.8.7-2009.10 (Ruby Enterprise Edition), which is installed on my OS X 10.6 system via rvm.

I got everything installed -- I think -- but when I run livereload, I get the message in the title of this issue, and nothing on the page ever seems to update.

Any suggestions?

**Comment by dottedmag** [comment]
From quick googling it looks like this bug is experienced by others with code other than LR. Please ask for the help from ree guys.

**Comment by dottedmag** [comment]
I am closing this issue as duplicate to newly created umbrella #24 (get rid of RubyCocoa).

**Comment by jathayde** [comment]
Hitting this without REE after installing RubyCocoa from source. Should I just revert to 1.3 until the rubycocoa issues are resolved?

**Comment by dottedmag** [comment]
Uhm, interesting. Yes, please revert until we get rid of RubyCocoa.

**Comment by NV** [comment]
I'm experiencing the same problem http://github.com/mockko/livereload/issues/issue/18/#issue/18/comment/439574 with RVM, Ruby 1.8.7 and livereload 1.4. However, LiveReload 1.3 doesn't work for me:

<pre>
➤ livereload 

Version:  1.3  (compatible with browser extension versions 1.3.x)
Port:     10083
Watching: /Users/nv/Sites/kulesh.info
  - extensions: .html .css .js .png .gif .jpg .php .php5 .py .rb .erb
  - excluding changes in: */dev/* */.git/* */.svn/* */.hg/*
/Users/nv/.rvm/gems/ruby-1.8.7-p302/gems/eventmachine-0.12.10/lib/eventmachine.rb:1266:in `watch_filename': Too many open files - failed to open file /Users/nv/Sites/kulesh.info/dev/thumbnails/1258801830_cover_img_0757edit_opt_thumbnail.jpg for registering with kqueue: Too many open files (Errno::EMFILE)
...
➤ cat .livereload 
config.exclusions << '*/dev/*'
</pre>


You see, `excluding changes in: */dev/*` doesn't work.

Any other options?

**Comment by dottedmag** [comment]
Non-working 1.3 is glaring offtopic here. Anyway, I can't bet excludes worked for 1.3

**Comment by NV** [comment]
I've disabled `rvm` and it works well &lt;/offtopic>
