### ISSUE TITLE
Chrome indicator does not indicate what page is actively monitored

### ISSUE THREAD

**Issue by dottedmag** [mockko/livereload#25]
How to reproduce:
- Start livereload. Enable it in Chrome for some page (icon turns green)
- Switch to another tab

What happens:
- Icon stays green.

What should happen:
- Icon should turn gray, and switch back to green only when you select tab with active page.

**Comment by dottedmag** [comment]
Implemented.

**Comment by NV** [comment]
LiveReload 1.5 Chrome extension and Safari extension have been released.
Closed by 38532bd8a0b3c556ef72d84d47fec1c3a6fd4d7a
Closed by 38532bd8a0b3c556ef72d84d47fec1c3a6fd4d7a
Closed by 38532bd8a0b3c556ef72d84d47fec1c3a6fd4d7a
