### ISSUE TITLE
Cannot start 'livereload' in Terminal.app.

### ISSUE THREAD

**Issue by gavinlaking** [mockko/livereload#27]
Just thought I'd give this gem a go, looks very interesting and could be a great time saver. I've installed the gem on my machine and when I move to my source directory and invoke 'livereload' I get a stack trace with:

../custom_require.rb:31:in `gem_original_require': no such file to load -- osx/foundation (LoadError)

To install:
SomeComputer:somedirectory me$ gem install livereload
Building native extensions.  This could take a while...
Successfully installed eventmachine-0.12.10
Successfully installed em-websocket-0.1.3
Successfully installed em-dir-watcher-0.9.4
Successfully installed ruby-json-1.1.2
Successfully installed livereload-1.4
5 gems installed
SomeComputer:somedirectory me$ livereload

I gather that osx foundation is part of RubyCocoa, but no mention of this is made in the documentation as a required gem. Any ideas/help would be appreciated.

Gav

**Comment by drewyeaton** [comment]
I'm having this problem as well.

**Comment by dottedmag** [comment]
Dup of #26

**Comment by dottedmag** [comment]
Closing
