### ISSUE TITLE
no such file to load -- osx/foundation (LoadError) 

### ISSUE THREAD

**Issue by ionas** [mockko/livereload#29]
- Found your awesome gem here: http://blog.envylabs.com/2010/07/livereload-screencast
- Followed your installation guides
- Platform: Mac OS X 10.6.4
- RVM
  rvm list
  rvm rubies
  ruby-1.8.7-p302 [ x86_64 ]
  => ruby-1.9.2-p0 [ x86_64 ]
  Both latest version, both tested, both giving the same error.

USERNAME@MACHINE: ~/Sites/rails/depot $ livereload

Version:  1.4  (compatible with browser extension versions 1.4.x)
Port:     35729
Watching: /Users/USERNAME/Sites/rails/depot
- extensions: .html .css .js .png .gif .jpg .php .php5 .py .rb .erb .haml
- excluding changes in: _/.git/_ _/.svn/_ _/.hg/_
- with a grace period of 0.05 sec after each change

LiveReload is waiting for browser to connect.
internal:lib/rubygems/custom_require:29:in `require': no such file to load -- osx/foundation (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac/rubycocoa_watcher.rb:2:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac.rb:16:in`block in initialize'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/invokers/subprocess_invoker.rb:61:in `call'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/invokers/subprocess_invoker.rb:61:in`start_subprocess'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/invokers/subprocess_invoker.rb:20:in `initialize'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac.rb:25:in`new'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/platform/mac.rb:25:in `initialize'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/monitor.rb:35:in`new'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/em-dir-watcher-0.9.4/lib/em-dir-watcher/monitor.rb:35:in `watch'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/livereload-1.4/lib/livereload.rb:175:in`restart_watching'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/livereload-1.4/lib/livereload.rb:243:in `block (2 levels) in run'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/livereload-1.4/lib/livereload.rb:243:in`each'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/livereload-1.4/lib/livereload.rb:243:in `block in run'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`call'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/livereload-1.4/lib/livereload.rb:215:in `run'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/gems/livereload-1.4/bin/livereload:51:in`<top (required)>'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/bin/livereload:19:in `load'
    from /Users/USERNAME/.rvm/gems/ruby-1.9.2-p0/bin/livereload:19:in`<main>'

my .livereload (nothing special I guess)

config.apply_js_live = true
config.apply_css_live = true
config.grace_period = 0.05

**Comment by dottedmag** [comment]
Dup of #26
