### ISSUE TITLE
Conflicts with Canvas

### ISSUE THREAD

**Issue by focalstrategy** [mockko/livereload#37]
More of a by the way than a bug, but if you draw on a canvas, changing the JS will draw again on the canvas without clearing it first.

You can tell livereload to refresh whole page, not just js in the .livereload file, or make sure you reset the canvas as the first part of your script.

Perhaps livereload could check if you are using the canvas API and default to reloading whole page in that case?

**Comment by NV** [comment]
It's not about canvas. The same happens with DOM nodes, [events](http://github.com/mockko/livereload/issues/closed#issue/31) and variables. Hope mockko guys someday pay attention to #36.

**Comment by NV** [comment]
Since #36 has been fixed, I close this issues.
