### ISSUE TITLE
Add exclude files

### ISSUE THREAD

**Issue by bitboxer** [mockko/livereload#4]
It would be great to have an option to exclude certain files from watching.

**Comment by andreyvit** [comment]
Do you mind giving a use case for this?

**Comment by bitboxer** [comment]
I have a webapp that, if in development mode, generates some files during page load. That creates an endless loop of reloads when i use livereload.

**Comment by andreyvit** [comment]
Oh clear. Yes, will add exclusions soon.

**Comment by andreyvit** [comment]
Done and released in version 1.3.

**Comment by dottedmag** [comment]
Implemented in 1.3
