### ISSUE TITLE
Windows 7 - could not find header: windows.h

### ISSUE THREAD

**Issue by kaivongcom** [mockko/livereload#50]
Getting the following problem on Windows 7: 

checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... no
checking for rb_thread_check_ints()... no
checking for rb_time_new()... no
checking for windows.h... no
could not find header: windows.h
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby187/bin/ruby

Gem files will remain installed in C:/Ruby187/lib/ruby/gems/1.8/gems/eventmachin
e-0.12.10 for inspection.
Results logged to C:/Ruby187/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/ext/gem
_make.out

**Comment by NV** [comment]
What did you run before this problem occurs? 
`gem install eventmachine --platform=win32`?

**Comment by NV** [comment]
I've found [the same problem with eventmachine](http://stackoverflow.com/questions/165488/installing-starling-on-windows/167250#167250). Tell me if it helps.

**Comment by kaivongcom** [comment]
You were correct... however their guide didn't help.  A quick googling about and I discovered that steps: 

1.)  gem install eventmachine-win32

Enabled the install to work... (instead of "gem install eventmachine --platform=win32"), then continuing on with your original suggest:- 

2).  gem install win32-changenotify win32-event livereload 

Complete the install.  Now to try it :)  Thanks for your help - much appreciated & happy ny to you!

**Comment by NV** [comment]
I just installed livereload on a Windows XP virtual machine. I had the same error. `gem install eventmachine-win32` works well. Thanks!
