### ISSUE TITLE
Firefox says wont find socket

### ISSUE THREAD

**Issue by lmartins** [mockko/livereload#58]
Cant make it to work. When i try to enable LR on Firefox it says "LiveReload Failed to establish connection WebSocket is not defined".

**Comment by NV** [comment]
Firefox < 4 does not support WebSockets.

**Comment by lmartins** [comment]
This was on Firefox 4 Beta 11, so it wont be the case.

**Comment by NV** [comment]
[WebSockets](https://developer.mozilla.org/en/WebSockets) might be disabled by default. Open about:config and change:

network.websocket.enabled true
network.websocket.override-security-block true

**Comment by lmartins** [comment]
Thanks! that solved the issue.
