### ISSUE TITLE
Hidden alert causes Safari to lock up on Windows

### ISSUE THREAD

**Issue by justmoon** [mockko/livereload#59]
When the connection fails the hidden alert() window causes Safari on Windows to stop responding to user input.

**Comment by dottedmag** [comment]
alert()s suck big time.

</troll>

**Comment by NV** [comment]
Closed by d1d332978f838d6963f5a61fc34051350c2f1668: Hidden alert causes Safari to lock up on Windows.
Better don&#39;t show it than locking up.

**Comment by NV** [comment]
Users won't see an error message, but I don't know a better solution at the moment.
