### ISSUE TITLE
Better file watching with FSSM

### ISSUE THREAD

**Issue by imathis** [mockko/livereload#6]
I'm wondering if you'd consider using FSSM for better file system watching. It supports using FSEvents on MacOS (with ruby 1.8), Inotify on GNU/Linux, and polling anywhere else. It works quite well: http://github.com/ttilley/fssm

**Comment by andreyvit** [comment]
Absolutely, that's on my list: http://twitter.com/livereload/status/18345779237

Also there's a bit of discussion at http://github.com/mockko/livereload/issues#issue/1

**Comment by andreyvit** [comment]
We couldn't use fssm since it's too naïve, but we made our own fs monitoring gem: em-dir-watcher. LiveReload 1.4 is now using it.
