### ISSUE TITLE
Internet Explorer extension

### ISSUE THREAD

**Issue by agileapricot** [mockko/livereload#61]
Some one had to request it. Since you only really need one modern browser and IE to do live testing in.

**Comment by agileapricot** [comment]
It seems IE9 might support websockets through silverlight http://html5labs.interoperabilitybridges.com/prototypes/available-for-download/websockets

**Comment by wailqill** [comment]
Closed without reason? If it's possible then why not? I'd love to use my guard/livereload setup in my vms with ie.

**Comment by replete** [comment]
Why is this closed? People still have to support IE8+, I was hoping to use this in my VM.

We could update the livereload JS snippet to fallback on a flash websocket polyfill.
