### ISSUE TITLE
Opera not working with xbrowser (despite renabling web sockets)

### ISSUE THREAD

**Issue by agileapricot** [mockko/livereload#62]
I renabled web sockets support in opera using this http://techdows.com/2010/12/enable-websockets-in-opera-11.html. However now I get this error...

LiveReload Failed to establish connection 'this._onopen.bind' is not a function

**Comment by NV** [comment]
Opera does not support Function.prototype.bind. I'll rewrite LiveReload to not use it. Thanks for the report!

**Comment by NV** [comment]
Fixed in fd556272b5e72708c258d24d039f196e0ccd2f40.

**Comment by agileapricot** [comment]
Awesome! Thanks.
