### ISSUE TITLE
Latest version breaks Firefox extension

### ISSUE THREAD

**Issue by lmartins** [mockko/livereload#64]
Used to work great, after i reinstalled livereload on top of a new ruby version, i get this error when i try to activate livereload firefox extension:

(this shows as a error dialog right in Firefox)
LiveReload You need to update the command-line tool to continue using LiveReload.

Extension version: 1.5.1
Command-line tool version: 1.6

Please run the following command to update your command-line tool:
    gem update livereload

**Comment by NV** [comment]
I forgot to upload new Firefox extension. Try to update it now. Thanks for heads up.
