### ISSUE TITLE
Incompatible Firefox extension

### ISSUE THREAD

**Issue by medihack** [mockko/livereload#65]
I just installed livereload on Firefox 4 as mentioned in the docs. Websocket is enabled.

I get this failure message:

<pre>
LiveReload You need to update the command-line tool to continue using LiveReload.

Extension version: 1.5.1
Command-line tool version: 1.6

Please run the following command to update your command-line tool:
    gem update livereload
</pre>

`gem update livereload` tells me that everything is up-to-date. The failure message is anyway misleading ... the command line has already a higher version then the extension.

**Comment by NV** [comment]
Just fixed livereload#64. Sorry about that.
