### ISSUE TITLE
Reload page on JS changes

### ISSUE THREAD

**Issue by KentonWhite** [mockko/livereload#7]
Love the gem.  Would really like to use it with automated javascript testing.  Problem is that some of the popular testing frameworks (I'm using Jasmine) don't get refreshed by livereload.  This seems to be because the page is not actually being reloaded when the JS is modified, so the new tests don't get run.

Is it possible to optionally configure livereload so that it will reload the page when a JS file is changed?

**Comment by andreyvit** [comment]
Will add today together with general configuration ability.

**Comment by KentonWhite** [comment]
Fantastic!  You Rock!

**Comment by dottedmag** [comment]
Implemented in 1.3

**Comment by andreyvit** [comment]
Done and released in version 1.3.
