### ISSUE TITLE
Monitoring does not work on a case-sensitive file system on a Mac

### ISSUE THREAD

**Issue by andreyvit** [mockko/livereload#76]
If the file system is formatted as case-sensitive, no changes are ever found. (Note that many other apps have problems in this configuration, including Xcode, so maybe just declare that it is not supported.)

**Comment by NV** [comment]
I'm not following. It seems to work well for me. I edit my stuff in `/Users/nv/Sites/somesite.com/public/` and I neved had this problem.

**Comment by andreyvit** [comment]
Are you on a case-sensitive FS?

**Comment by NV** [comment]
I just checked:

```
mkdir a
mkdir A
mkdir: A: File exists
```

So I'm not.

**Comment by andreyvit** [comment]
Actually I looked at this bug recently, and I was not on a case-sensitive FS either. File system notifications were just broken for some folders, somehow. After doing some renaming/moving magic those work again. So I believe this issues is unrelated to LR.
