### ISSUE TITLE
Excluding extensions

### ISSUE THREAD

**Issue by grimen** [mockko/livereload#8]
Nice updates on the config, but it seems to be impossible to reset tracked extensions.

Example:

<pre>
config.exts = %w[.haml .sass]
</pre>

only appends them once again, not setting the extensions to track. A bit annoying to track PHP and PY files in  Rails app that is.

**Comment by andreyvit** [comment]
Okay, I think I know an easy way to fix this, will have a look in one of the next versions.

**Comment by andreyvit** [comment]
This is now possible in LiveReload 1.4. Please update and test.
