### ISSUE TITLE
to_json complains in Rails 3.1.x  apps

### ISSUE THREAD

**Issue by mattsears** [mockko/livereload#80]
It appears livereload's dependency on ruby-json is causing `to_json` to throw "wrong number of arguments (0 for 1)" in Rails 3.1.x apps.

I'm running Rails 3.1.0.rc1 and Ruby 1.9.2

**Comment by guitsaru** [comment]
It does the same in 3.0.9.  The dependency on ruby-json also completely breaks activesupport's json handling in other ways:

``` (ruby)
User.first.to_json => "\"#<User:0x007fcfe7fd25a0>\""
```

Instead of the desired attributes as json

**Comment by logankoester** [comment]
This appears to be fixed by replacing 'ruby-json' with 'json', see pull request https://github.com/mockko/livereload/pull/90
