### ISSUE TITLE
Livereload Safari extension does not handle https 

### ISSUE THREAD

**Issue by romanrudenko** [mockko/livereload#81]
When LiveReload Safari extension is activated on https pages, it results in "Browser URL: undefined" sent to server console and no live reloading. This happens because the extension is packaged without permission to access secure pages.

 I managed to get the extension to work with https by adding &lt;key&gt;Include Secure Pages&lt;/key&gt;&lt;true/&gt; before &lt;key&gt;Level&lt;/key&gt;&lt;string&gt;All&lt;/string&gt; inside Info.plist. Is this flag omitted for a reason? Or is it an oversight?

**Comment by NV** [comment]
Thanks, added in 38e565dec28e4147752a34a9ae32da2045cae9da. It was an oversight.

"Browser URL: undefined" has been fixed in [LiveReload 1.6.2](https://github.com/downloads/mockko/livereload/LiveReload-1.6.2.safariextz).
