### ISSUE TITLE
Firefox 7(.0.1) Support?

### ISSUE THREAD

**Issue by brendanjerwin** [mockko/livereload#98]

**Comment by NV** [comment]
https://addons.mozilla.org/en-US/firefox/addon/livereload/versions/?page=1#version-0.6.4 should work up to the latest Aurora build. What problem do you have?

**Comment by NV** [comment]
You have to manually install LiveReload 0.6.4. It hasn't been reviewed yet, so auto-update doesn't work. The review process usually takes few weeks.

They would probably release the new version of Firefox at the time it will be reviewed. Mozilla's max-version policy is truly brain dead.

**Comment by brendanjerwin** [comment]
I got it installed, but it silently does nothing. Pushing the button, once I've added it to the toolbar, does nothing.

I'm using guard-livereload 1.6, the chrome add-in (1.6) works fine.

I've reset my firefox settings and removed all other extensions.

How can I find out what it thinks is going on?

**Comment by redfellow** [comment]
I have the same problem. I add the LR button and I can verify with Chrome that the websocket is listening and works. However pushing the button does not do anything. Mouseovering the button shows "Enable Livereload", and the tooltip is the same even after a click.

Ubuntu 11.04 & Firefox 7.0.1

edit: And now all out of a sudden, the button does turn green.

CLI output:
Browser URL: http://r86.com/node/93/edit
Modified: custom-styles.css

Yet no refresh happends. My CSS markup is as follows (commentbox breaks it, but its valid):

<style type="text/css" media="screen">@import url("http://r86.com/sites/default/themes/admin_seven/custom-styles.css?lsp4x0");</style>


The domain is set in /hosts and doesn't really exist.

**Comment by brendanjerwin** [comment]
**UPDATE**: It just started working for me as well. Weird, but I'll take it.
